version: '3.9'
services:
  postgres-server:
    image: postgres
    container_name: some-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '18pass11'
  project-server:
    image: project-rsikspr
    depends_on:
      - postgres-server
