spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "18pass11"
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQL82Dialect: org.hibernate.dialect.PostgreSQL82Dialect
